name: guillermo-app
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.d/
      - ./nginx/html:/var/www/html
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - php

  php:
    container_name: php
    build:
      context: ./php
      dockerfile: Dockerfile
    working_dir: /var/www/html/
    volumes:
      - ./nginx/html:/var/www/html/
    ports:
      - 9000:9000
    restart: always
    depends_on:
      mysql:
        condition: service_healthy

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      retries: 10
volumes:
  mysqldata:
